version: '3'
services:
    reverse-proxy:
        build: reverse-proxy
        container_name: nginx-rp
        ports:
            - 443:443
            - 80:80

    cc-apps-experiences:
        build: experiences
        container_name: experiences
        ports:
            - 5004:5004

    cc-apps-rewards:
        build: rewards
        container_name: rewards123
        ports:
            - "5002:5002"
